version: '3'

services:
  jupyter0:
    image: amy/pytorch
    volumes:
      - /mnt/sub/docker_volumes/amy-vol/_data:/workspace
    ports:
      - "29029:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 0
              capabilities: [gpu]
    command: jupyter lab --allow-root --config /workspace/jupyter_notebook_config.py

  tensorboard0:
    image: amy/pytorch
    volumes:
      - /mnt/sub/docker_volumes/amy-vol/_data:/workspace
    ports:
      - "29030:8889"
    command: tensorboard --logdir=log/tensorboard --port=8889 --host=0.0.0.0