version: '3'

services:
  jupyter0:
    image: amy/pytorch
    volumes:
      - /mnt/sub/docker_volumes/amy-vol/_data:/workspace
    ports:
      - "29029:8888"
    runtime: nvidia
    command: jupyter lab --allow-root --config /workspace/jupyter_notebook_config.py

  tensorboard0:
    image: amy/pytorch
    volumes:
      - /mnt/sub/docker_volumes/amy-vol/_data:/workspace
    ports:
      - "29030:8889"
    command: tensorboard --logdir=log/tensorboard --port=8889 --host=0.0.0.0
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - /mnt/sub/docker_volumes/amy-vol/mongo_db:/data/db
    ports:
      - "29019:27017"
    environment:
      - MONGO_USERNAME=name
      - MONGO_PASSWORD=passwd
      - MONGO_DATABASE=test